# Generated by Django 3.0.3 on 2020-03-29 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50, verbose_name='Nama')),
                ('umur', models.IntegerField(verbose_name='Umur')),
                ('emel', models.EmailField(max_length=254, verbose_name='Email')),
            ],
        ),
    ]
